In [1]:
import pandas as pd
import numpy as np

In [2]:
#loading the dataset
df= pd.read_csv(r"C:\Shambhavi\Finance Project Credit Risk Assessment\Dataset\Credit_Risk_Dataset (2).csv")

In [3]:
#Fetching first 5 rows of dataset
df.head(5)

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,35000,14.27,1,0.55,Y,4

In [4]:
#Fetching last 5 rows of dataset
df.tail(5)

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
32576,57,53000,MORTGAGE,1.0,PERSONAL,5800,13.16,0,0.11,N,30
32577,54,120000,MORTGAGE,4.0,PERSONAL,17625,7.49,0,0.15,N,19
32578,65,76000,RENT,3.0,HOMEIMPROVEMENT,35000,10.99,1,0.46,N,28
32579,56,150000,MORTGAGE,5.0,PERSONAL,15000,11.48,0,0.10,N,26
32580,66,42000,RENT,2.0,MEDICAL,6475,9.99,0,0.15,N,30

In [5]:
#Displaying column names 
df.columns

Index(['person_age', 'person_income', 'person_home_ownership',
       'person_emp_length', 'loan_intent', 'loan_amnt', 'loan_int_rate',
       'loan_status', 'loan_percent_income', 'cb_person_default_on_file',
       'cb_person_cred_hist_length'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32581 non-null  int64
 1   person_income               32581 non-null  int64
 2   person_home_ownership       32581 non-null  str
 3   person_emp_length           31686 non-null  float64
 4   loan_intent                 32581 non-null  str
 5   loan_amnt                   32581 non-null  int64
 6   loan_int_rate               29465 non-null  float64
 7   loan_status                 32581 non-null  int64
 8   loan_percent_income         32581 non-null  float64
 9   cb_person_default_on_file   32581 non-null  str
 10  cb_person_cred_hist_length  32581 non-null  int64
dtypes: float64(3), int64(5), str(3)
memory usage: 2.7 MB

In [7]:
#Displaying summary statistics
df.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,32581.000000,3.258100e+04,31686.000000,32581.000000,29465.000000,32581.000000,32581.000000,32581.000000
mean,27.734600,6.607485e+04,4.789686,9589.371106,11.011695,0.218164,0.170203,5.804211
std,6.348078,6.198312e+04,4.142630,6322.086646,3.240459,0.413006,0.106782,4.055001
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.850000e+04,2.000000,5000.000000,7.900000,0.000000,0.090000,3.000000
50%,26.000000,5.500000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,7.920000e+04,7.000000,12200.000000,13.470000,0.000000,0.230000,8.000000
max,144.000000,6.000000e+06,123.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

In [8]:
#Checking for null values
df.isnull().sum()

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length              895
loan_intent                      0
loan_amnt                        0
loan_int_rate                 3116
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

In [9]:
#Filling null values with median
emp_median = df['person_emp_length'].median()
df['person_emp_length'] = df['person_emp_length'].fillna(emp_median)
int_rate_median = df['loan_int_rate'].median()
df['loan_int_rate'] = df['loan_int_rate'].fillna(int_rate_median)

In [10]:
# Verify that all null values are gone
print(df.isnull().sum())

person_age                    0
person_income                 0
person_home_ownership         0
person_emp_length             0
loan_intent                   0
loan_amnt                     0
loan_int_rate                 0
loan_status                   0
loan_percent_income           0
cb_person_default_on_file     0
cb_person_cred_hist_length    0
dtype: int64

In [11]:
#Checking for duplicate values
df.duplicated().sum()

np.int64(165)

In [12]:
#Fixing duplicate 165 rows
df=df.drop_duplicates()

In [13]:
#Verify that all duplicates are gone
df.duplicated().sum()

np.int64(0)

In [14]:
#Checking data types
df.dtypes

person_age                      int64
person_income                   int64
person_home_ownership             str
person_emp_length             float64
loan_intent                       str
loan_amnt                       int64
loan_int_rate                 float64
loan_status                     int64
loan_percent_income           float64
cb_person_default_on_file         str
cb_person_cred_hist_length      int64
dtype: object

In [15]:
# Check unique categories and their formats for home ownership
print(df['person_home_ownership'].value_counts())
print("-" * 40)

# Check unique categories and their formats for loan intent
print(df['loan_intent'].value_counts())

person_home_ownership
RENT        16378
MORTGAGE    13369
OWN          2563
OTHER         106
Name: count, dtype: int64
----------------------------------------
loan_intent
EDUCATION            6411
MEDICAL              6042
VENTURE              5682
PERSONAL             5498
DEBTCONSOLIDATION    5189
HOMEIMPROVEMENT      3594
Name: count, dtype: int64

In [16]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (2.4.2)
Requirement already satisfied: scipy>=1.10.0 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (2.23.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (3.6.0)

In [17]:
#Performing Normalisation
# Create a copy of the dataframe
df_normalized = df.copy()

# List of numeric columns to scale
numeric_cols = ['person_age', 'person_income', 'loan_amnt', 'loan_int_rate']

# Manual Min-Max Scaling formula: (X - min) / (max - min)
for col in numeric_cols:
    df_normalized[col] = (df_normalized[col] - df_normalized[col].min()) / (df_normalized[col].max() - df_normalized[col].min())

# View the result
df_normalized[numeric_cols].head()

   person_age  person_income  loan_amnt  loan_int_rate
0    0.016129       0.009173   1.000000       0.595506
1    0.008065       0.000934   0.014493       0.321348
2    0.040323       0.000934   0.144928       0.418539
3    0.024194       0.010257   1.000000       0.551124
4    0.032258       0.008406   1.000000       0.497191

In [18]:
#Performing Standardisation
from sklearn.preprocessing import StandardScaler

# Initialize the scaler
standard_scaler = StandardScaler()

# Create a copy of the dataframe
df_standardized = df.copy()

# Apply Standardization to key numeric columns
df_standardized[numeric_cols] = standard_scaler.fit_transform(df_standardized[numeric_cols])

# View the result (values will scale around 0)
df_standardized[numeric_cols].head()

   person_age  person_income  loan_amnt  loan_int_rate
0   -0.904471      -0.114354   4.018287       1.623527
1   -1.061852      -0.910941  -1.359219       0.040655
2   -0.432327      -0.910941  -0.647491       0.601796
3   -0.747089      -0.009540   4.018287       1.367283
4   -0.589708      -0.188530   4.018287       1.055898

In [19]:
#Identifying and Removing Outliers
# 1. Inspect extreme values before filtering
print("Max Age before:", df['person_age'].max())
print("Max Employment Length before:", df['person_emp_length'].max())

# 2. Filter out unrealistic rows
df = df[(df['person_age'] <= 100) & (df['person_emp_length'] <= 60)]

# 3. Confirm clean boundaries
print("\nMax Age after:", df['person_age'].max())
print("Max Employment Length after:", df['person_emp_length'].max())

Max Age before: 144
Max Employment Length before: 123.0

Max Age after: 94
Max Employment Length after: 41.0

In [20]:
#Checking Data Formats
# List of text/categorical columns
text_cols = ['person_home_ownership', 'loan_intent', 'cb_person_default_on_file']

# Clean white spaces and force uppercase formatting
for col in text_cols:
    df[col] = df[col].astype(str).str.strip().str.upper()

# Verify uniform formatting
print(df['person_home_ownership'].unique())

<StringArray>
['OWN', 'MORTGAGE', 'RENT', 'OTHER']
Length: 4, dtype: str

In [21]:
#Grouping Ages
# Define the age boundary brackets and their corresponding business labels
age_bins = [0, 25, 35, 50, 100]
age_labels = ['Young Adult (<25)', 'Core Professional (25-35)', 'Mid-Career (35-50)', 'Senior (50+)']

# Create the engineered categorical column
df['age_group'] = pd.cut(df['person_age'], bins=age_bins, labels=age_labels, right=False)

# Check the distribution of your new column
print(df['age_group'].value_counts())

age_group
Core Professional (25-35)    16115
Young Adult (<25)            12220
Mid-Career (35-50)            3739
Senior (50+)                   335
Name: count, dtype: int64

In [22]:
#Grouping Incomes
# Define income thresholds based on common portfolio tiers
# (0 to 35k, 35k to 70k, 70k to 100k, and 100k+)
income_bins = [0, 35000, 70000, 100000, float('inf')]
income_labels = ['Low Income (<35k)', 'Medium Income (35k-70k)', 'High Income (70k-100k)', 'HNW (>100k)']

# Create the engineered income slab column
df['income_slab'] = pd.cut(df['person_income'], bins=income_bins, labels=income_labels, right=False)

# Check the distribution of income segments
print(df['income_slab'].value_counts())

income_slab
Medium Income (35k-70k)    15236
High Income (70k-100k)      6442
Low Income (<35k)           6184
HNW (>100k)                 4547
Name: count, dtype: int64

In [23]:
#Exporting clean dataset 
# Save the final cleaned dataframe to a new CSV file
df.to_csv(r"C:\Shambhavi\Finance Project Credit Risk Assessment\Dataset\Cleaned_Credit_Risk_Dataset.csv", index=False)
print("Dataset cleaned, engineered, and successfully exported!")

Dataset cleaned, engineered, and successfully exported!